### ISSUE TITLE
KNE Lab con BGP, error with p1 and p2

### ISSUE THREAD

**Issue by yennym3** [open-traffic-generator/otg-examples#56]
Hi, I am testing the KNE Lab with BGP and I am getting this error, this corresponds to not having access to the "ghcr.io/open-traffic-generator/licensed/ixia-c-protocol-engine" image?.

When executing this:

> kubectl exec -it otgen -- /bin/bash
export OTG_API="https://service-https-keng-controller.keng-ceos.svc.cluster.local:8443"
otgen create device -n otg1 -p p1 -l eth1 --ip 192.0.2.1 --prefix 30 --gw 192.0.2.2 | \
otgen add device    -n otg2 -p p2 -l eth2 --ip 192.0.2.5 --prefix 30 --gw 192.0.2.6 | \
otgen add bgp -d otg1 --asn 1111 --route 198.51.100.0/24 | \
otgen add bgp -d otg2 --asn 2222 --route 203.0.113.0/24  | \
otgen add flow -n f-1-2 --tx otg1 --rx otg2 --src 198.51.100.1 --dst 203.0.113.1 --count 1000 --rate 100 --size 128 | \
otgen add flow -n f-2-1 --tx otg2 --rx otg1 --dst 198.51.100.1 --src 203.0.113.1 --count 2000 --rate 200 --size 256 | \
otgen --log info run -k -m flow | otgen transform -m flow | otgen display -m table
exit

this is the error
> INFO[0000] Applying OTG config...
ERRO[0000] OTG API error code: 500
ERRO[0000] OTG API error kind: internal
ERRO[0000] OTG API error messages:
ERRO[0000] Protocol service for port "p2" is not registered
ERRO[0000] Error occurred while setting Protocol config for user common:Protocol service for port "p1" is not registered
FATA[0000] Fatal OTG error, exiting...

**Comment by bortok** [comment]
Hi @yennym3 mostly likely that is the cause. You should be able to pull `docker pull ghcr.io/open-traffic-generator/licensed/ixia-c-protocol-engine` and that requires authentication. There are a good news on that – we plan to openly publish `ixia-c-protocol-engine` in a few weeks. It would have certain capabilities available w/o a need for a license. If it works for you, I would recommend to wait for that moment. Once it is published, I'll be updating the `otg-examples` to use the public images.

**Comment by bortok** [comment]
Hi @yennym3 it took us a while but now this lab can be used without any special access / authentication.

**Comment by arkajyoti-cloud** [comment]
the protocol engine can be downloaded now without any issues.
